#+title: dape-cmake
# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-

* Introduction
Debug an executable generated with CMake using dape + lldb-dap.

* Dependency
- [[https://github.com/IwachanOrigin/cmake-build][cmake-build]]

* Install
#+begin_src emacs-lisp
  (use-package dape-cmake
    :vc (:fetcher github :repo IwachanOrigin/dape-cmake))
#+end_src

* How to use
1) Open a C++ implementation file or header file.
2) M-x ~cmake-configure~ RET. \\
   Temporary build artifacts will be generated in the build folder.
3) M-x ~cmake-build-debug~ or ~cmake-build-release~ RET. \\
   The build is executed, and an executable file is generated.
4) M-x ~dape-cmake-debug~ RET. \\
   Start the debug process.

* Optional
To set arguments, run M-x ~dape-cmake-set-args~ and configure them via the prompt.
A .dape-args file will be created in the project root (i.e., the directory containing the top-level CMakeLists.txt).
If a .dape-args file already exists, it will be parsed and the arguments will be loaded automatically.

* Custom Value
** cmake-find-exec
| custom value         | default value | description                                                                  |
|----------------------+---------------+------------------------------------------------------------------------------|
| dape-cmake-args-file | .dape-args    | The name of the file that saves debug arguments, placed in the project root. |
|                      |               |                                                                              |


